#pragma config(Sensor, in1,    BallDetect,     sensorReflection)
#pragma config(Sensor, in2,    ArmPotentiometer, sensorPotentiometer)
#pragma config(Motor,  port1,           LMotor,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          RMotor,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int preloadPosition = 1220;

const int marbleLightThreshold = 190;

bool ballLaunch = false;

const long cycleTime = 15000;
unsigned long launchTimer;

void timerBegin(){
	launchTimer = nSysTime + cycleTime;
}

bool timerIsReady(){
	return nSysTime >= launchTimer;
}

const int launchPower = 65;
void driveLauncher(int speed){
	motor[LMotor] = speed;
	motor[RMotor] = speed;
}

const int stopPower = 5;
void stopLauncher(){
	driveLauncher(stopPower);
}

void launchBall(){
	timerBegin();
	ballLaunch = true;
}

int marbleReadyCounter = 0;

bool isMarbleReady(){
	bool marbleDetected = SensorValue[BallDetect] > marbleLightThreshold;
	if(marbleDetected){
		marbleReadyCounter++;
	}
	else{
		marbleReadyCounter = 0;
	}
	return marbleReadyCounter >= 10 && marbleDetected;
}

task launcherControl{
	float launcherKp = 1.0;
	while(true){
		if(ballLaunch){
			wait1Msec(150);
			driveLauncher(launchPower);
			while(SensorValue[ArmPotentiometer] > preloadPosition - 10){
				wait1Msec(10);
			}
			wait1Msec(50);
			stopLauncher();
			ballLaunch = false;
		}

		if(SensorValue[ArmPotentiometer] < preloadPosition){
			int error = preloadPosition - SensorValue[ArmPotentiometer];
			int driveSpeed = launcherKp * error;

			driveSpeed = abs(driveSpeed)>launchPower?launchPower*sgn(driveSpeed):0;

			driveLauncher(driveSpeed);
		}
		//else if(false){
		//}
		else{
			stopLauncher();
		}

		wait1Msec(10);
	}
}

task main()
{
	startTask(launcherControl);

	while(true){
		if(isMarbleReady() && timerIsReady()){
			launchBall();
		}

		wait1Msec(10);
	}
}
